# This is the config file for ${project.name} v${project.version}

# localized language support
language: en-US

# If this list is empty, all worlds will be added to the enabled worlds list
enabled-worlds:
#  - enabled_world1
#  - enabled_world2

# These worlds will be removed from the enabled worlds list
disabled-worlds:
  - disabled_world1
  - disabled_world2

# RoadBlock tool material
tool-material: GOLD_PICKAXE

# How far to search for adjacent road blocks from clicked location
spread-distance: 100

# prevent mobs from targeting players farther than this distance when on roads
target-distance: 5

# materials to be considered road blocks
materials:
  - STEP
  - DOUBLE_STEP
  - COBBLESTONE
  - COBBLESTONE_STAIRS
  - MOSSY_COBBLESTONE
  - SMOOTH_BRICK
  - SMOOTH_STAIRS
  - GRASS_PATH
