name: ${project.name}
main: com.winterhaven_mc.roadblock.PluginMain
author: ${project.author}
version: ${project.version}
softdepend: [Multiverse-Core]

commands:
  roadblock:
    aliases: rb
    description: This is the RoadBlock command.
    usage: /<command> [command]

permissions:
  roadblock.help:
    description: Display help for RoadBlock commands.
    default: op

  roadblock.status:
    description: Allows display of config settings.
    default: op

  roadblock.reload:
    description: Allows reloading the config file.
    default: op

  roadblock.break:
    description: Allows breaking RoadBlock protected blocks.
    default: op

  roadblock.set:
    description: Allows setting RoadBlock protection on blocks.
    default: op

  roadblock.unset:
    description: Allows removing RoadBlock protection on blocks.
    default: op

  roadblock.tool:
    description: Allows creating a RoadBlock tool in inventory.
    default: op

  roadblock.show:
    description: Allows highlighting blocks within specified distance.
    default: op

  roadblock.admin:
    description: Allows all admin commands
    default: op
    children:
      roadblock.help: true
      roadblock.reload: true
      roadblock.set: true
      roadblock.show: true
      roadblock.status: true
      roadblock.tool: true
      roadblock.unset: true
